version: '3.3'

services:
  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    networks: #define uma rede especifica
      - backend

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    networks: #define uma rede especifica
      - backend

volumes:
  db_data: {}
networks:
  backend: #declara a rede que foi inserida acima
    driver: bridge #define o driver para a rede
