--- #utilizado para separar arquivos/objetos
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
  type: LoadBalancer
--- #utilizado para separar arquivos/objetos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-depoyment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: vitordemarqui/flash-kub-projeto:3
